openapi: 3.1.0
info:
  title: Sports Headlines API
  version: 1.0.0
servers:
  - url: https://sports-headlines-api.onrender.com
paths:
  /headlines:
    get:
      summary: Get latest sports headlines
      operationId: getHeadlines
      responses:
        "200":
          description: A list of sports headlines
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    summary:
                      type: string
                    link:
                      type: string
    /reddit_nhl:
      get:
        summary: Get top trending posts from r/nhl subreddit (prioritizes Discussion flair)
        operationId: getRedditNhl
        responses:
          "200":
            description: A list of top Reddit posts from r/nhl
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      flair:
                        type: string
                      upvotes:
                        type: integer
                      link:
                        type: string
    
